// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/shopspring/decimal"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOracle creates a new instance of MockOracle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOracle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOracle {
	mock := &MockOracle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOracle is an autogenerated mock type for the Oracle type
type MockOracle struct {
	mock.Mock
}

type MockOracle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOracle) EXPECT() *MockOracle_Expecter {
	return &MockOracle_Expecter{mock: &_m.Mock}
}

// FetchPrice provides a mock function for the type MockOracle
func (_mock *MockOracle) FetchPrice(ctx context.Context, coingeckoID string, fiatCurrency string) (decimal.Decimal, error) {
	ret := _mock.Called(ctx, coingeckoID, fiatCurrency)

	if len(ret) == 0 {
		panic("no return value specified for FetchPrice")
	}

	var r0 decimal.Decimal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (decimal.Decimal, error)); ok {
		return returnFunc(ctx, coingeckoID, fiatCurrency)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) decimal.Decimal); ok {
		r0 = returnFunc(ctx, coingeckoID, fiatCurrency)
	} else {
		r0 = ret.Get(0).(decimal.Decimal)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, coingeckoID, fiatCurrency)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOracle_FetchPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchPrice'
type MockOracle_FetchPrice_Call struct {
	*mock.Call
}

// FetchPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - coingeckoID string
//   - fiatCurrency string
func (_e *MockOracle_Expecter) FetchPrice(ctx interface{}, coingeckoID interface{}, fiatCurrency interface{}) *MockOracle_FetchPrice_Call {
	return &MockOracle_FetchPrice_Call{Call: _e.mock.On("FetchPrice", ctx, coingeckoID, fiatCurrency)}
}

func (_c *MockOracle_FetchPrice_Call) Run(run func(ctx context.Context, coingeckoID string, fiatCurrency string)) *MockOracle_FetchPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOracle_FetchPrice_Call) Return(decimal1 decimal.Decimal, err error) *MockOracle_FetchPrice_Call {
	_c.Call.Return(decimal1, err)
	return _c
}

func (_c *MockOracle_FetchPrice_Call) RunAndReturn(run func(ctx context.Context, coingeckoID string, fiatCurrency string) (decimal.Decimal, error)) *MockOracle_FetchPrice_Call {
	_c.Call.Return(run)
	return _c
}
