linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - revive
    - gosec

linters-settings:
  revive:
    rules:
      - name: exported
        disabled: true

issues:
  exclude-dirs:
    - internal/docs
    - internal/mocks
