// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockKMS creates a new instance of MockKMS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKMS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKMS {
	mock := &MockKMS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKMS is an autogenerated mock type for the KMS type
type MockKMS struct {
	mock.Mock
}

type MockKMS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKMS) EXPECT() *MockKMS_Expecter {
	return &MockKMS_Expecter{mock: &_m.Mock}
}

// CreateKey provides a mock function for the type MockKMS
func (_mock *MockKMS) CreateKey(ctx context.Context, name string) error {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKMS_CreateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKey'
type MockKMS_CreateKey_Call struct {
	*mock.Call
}

// CreateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockKMS_Expecter) CreateKey(ctx interface{}, name interface{}) *MockKMS_CreateKey_Call {
	return &MockKMS_CreateKey_Call{Call: _e.mock.On("CreateKey", ctx, name)}
}

func (_c *MockKMS_CreateKey_Call) Run(run func(ctx context.Context, name string)) *MockKMS_CreateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockKMS_CreateKey_Call) Return(err error) *MockKMS_CreateKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKMS_CreateKey_Call) RunAndReturn(run func(ctx context.Context, name string) error) *MockKMS_CreateKey_Call {
	_c.Call.Return(run)
	return _c
}

// Decrypt provides a mock function for the type MockKMS
func (_mock *MockKMS) Decrypt(ctx context.Context, name string, ciphertext string) ([]byte, error) {
	ret := _mock.Called(ctx, name, ciphertext)

	if len(ret) == 0 {
		panic("no return value specified for Decrypt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, error)); ok {
		return returnFunc(ctx, name, ciphertext)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = returnFunc(ctx, name, ciphertext)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, ciphertext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMS_Decrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrypt'
type MockKMS_Decrypt_Call struct {
	*mock.Call
}

// Decrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - ciphertext string
func (_e *MockKMS_Expecter) Decrypt(ctx interface{}, name interface{}, ciphertext interface{}) *MockKMS_Decrypt_Call {
	return &MockKMS_Decrypt_Call{Call: _e.mock.On("Decrypt", ctx, name, ciphertext)}
}

func (_c *MockKMS_Decrypt_Call) Run(run func(ctx context.Context, name string, ciphertext string)) *MockKMS_Decrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKMS_Decrypt_Call) Return(bytes []byte, err error) *MockKMS_Decrypt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockKMS_Decrypt_Call) RunAndReturn(run func(ctx context.Context, name string, ciphertext string) ([]byte, error)) *MockKMS_Decrypt_Call {
	_c.Call.Return(run)
	return _c
}

// Encrypt provides a mock function for the type MockKMS
func (_mock *MockKMS) Encrypt(ctx context.Context, name string, plaintext []byte) (string, error) {
	ret := _mock.Called(ctx, name, plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return returnFunc(ctx, name, plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = returnFunc(ctx, name, plaintext)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, name, plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKMS_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockKMS_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - plaintext []byte
func (_e *MockKMS_Expecter) Encrypt(ctx interface{}, name interface{}, plaintext interface{}) *MockKMS_Encrypt_Call {
	return &MockKMS_Encrypt_Call{Call: _e.mock.On("Encrypt", ctx, name, plaintext)}
}

func (_c *MockKMS_Encrypt_Call) Run(run func(ctx context.Context, name string, plaintext []byte)) *MockKMS_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockKMS_Encrypt_Call) Return(s string, err error) *MockKMS_Encrypt_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockKMS_Encrypt_Call) RunAndReturn(run func(ctx context.Context, name string, plaintext []byte) (string, error)) *MockKMS_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}
